language: bash

before_install:
  - sudo apt-get update && sudo apt-get install -y shellcheck
  - sudo apt-get install imagemagick 
  - sudo apt-get install p7zip-full
  - sudo apt-get install ghostscript

script:
  - wget "https://c4pr1c3.gitee.io/linuxsysadmin/exp/chap0x04/worldcupplayerinfo.tsv"
  - wget "https://c4pr1c3.github.io/LinuxSysAdmin/exp/chap0x04/web_log.tsv.7z"
  - 7z x -ot web_log.tsv.7z
  - ls -l
  - bash img_process.sh -h
  - bash img_process.sh -q 80
  - bash img_process.sh -d 70%
  - bash img_process.sh -w 5 lychee
  - bash img_process.sh -p pre
  - bash img_process.sh -s post
  - bash img_process.sh -t
  - echo "=============================="
  - bash statistics_player.sh -h
  - bash statistics_player.sh -s
  - bash statistics_player.sh -c
  - bash statistics_player.sh -l
  - bash statistics_player.sh -a
  - echo "=============================="
  - bash statistics_top100.sh -h
  - bash statistics_top100.sh -o
  - bash statistics_top100.sh -i
  - bash statistics_top100.sh -u
  - bash statistics_top100.sh -s
  - bash statistics_top100.sh -f
  - bash statistics_top100.sh -g /icons/menu.xbm
  - echo "=============================="
  - shellcheck img_process.sh
  - shellcheck statistics_player.sh
  - shellcheck statistics_top100.sh

notifications:
  email:
    on_success: never
